export interface Game {
  title: string;
  url: string;
  description: string;
  highlights?: string;
  features?: string[];
  category: string;
  subcategory?: string;
  icon?: string;
}

export const games: Game[] = [
  {
    title: 'GameNGen',
    url: 'https://gamengen.github.io/',
    description: 'Google\'s AI game engine that can generate playable DOOM game scenes in real-time, with a frame rate of 20 FPS, so realistic that 60% of players cannot distinguish between real and generated content.',
    highlights: 'Shows the potential of AI replacing traditional programming, potentially changing the game development industry.',
    category: 'Game Design',
    subcategory: 'Game Engine',
    icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/2560px-Google_2015_logo.svg.png'
  },
  {
    title: 'Scenario',
    url: 'https://www.scenario.com/',
    description: 'An AI-driven game asset generation tool focused on helping developers quickly create high-quality game assets (such as characters, scenes, etc.).',
    highlights: 'Suitable for independent developers, generated assets can be directly used in game engines.',
    category: 'Game Design',
    subcategory: 'Game Engine'
  },
  {
    title: 'Inworld',
    url: 'https://inworld.ai/',
    description: 'An AI character creation platform that allows developers to design NPCs (non-player characters) with personality, emotion, and dialogue capabilities.',
    highlights: 'Enhances the realism of game worlds, adopted by some independent games.',
    category: 'Game Design',
    subcategory: 'Game Engine'
  },
  {
    title: 'Promethean AI',
    url: 'https://www.prometheanai.com/',
    description: 'A pioneer in game environment creation. This tool leverages the power of artificial intelligence to automate the process of building 3D environments, allowing game developers to easily create rich, detailed worlds.',
    highlights: 'Can generate various environments based on simple descriptions.',
    features: [
      'Automatically generates 3D environments using AI',
      'Natural language interface for easy interaction',
      'Supports multiple environment types'
    ],
    category: 'Game Design',
    subcategory: 'Game Engine'
  },
  {
    title: 'Juicy AI',
    url: 'https://juicy-ai.com/my-character',
    description: 'An entertainment platform centered on AI-generated characters, supporting user interaction with virtual characters, including light gamification elements.',
    highlights: 'User-friendly interface, vivid character design, strong interactivity.',
    category: 'Game Design',
    subcategory: 'Story Design'
  },
  {
    title: 'Character.ai',
    url: 'https://character.ai/',
    description: 'AI-driven character interaction platform',
    category: 'Game Design',
    subcategory: 'Story Design'
  },
  {
    title: 'Death by AI',
    url: 'https://deathbyai.gg/',
    description: 'AI-driven action game platform',
    category: 'ACT'
  },
  {
    title: 'AI Town',
    url: 'https://www.convex.dev/ai-town',
    description: 'AI-driven virtual town simulation game',
    category: 'SLG'
  },
  {
    title: 'Fly Pieter',
    url: 'https://fly.pieter.com/',
    description: 'A multiplayer online flight simulation game, combining simulation (SIM) and massively multiplayer online (MMO) elements.',
    highlights: 'Players can experience directly through the web, no download or update required, simple operation, supports real-time multiplayer interaction, can accommodate up to 200 players online simultaneously',
    category: 'SLG'
  },
  {
    title: 'Oasis',
    url: 'https://oasis.decart.ai/welcome',
    description: 'The world\'s first real-time AI-generated open-source game, jointly developed by Etched and Decart AI. Similar to Minecraft\'s sandbox style, completely generated by AI models, no traditional game engine required.',
    highlights: 'Free online experience, open source, showcasing the cutting-edge potential of AI in game generation.',
    category: 'SLG',
    subcategory: 'Sandbox Simulation'
  },
  {
    title: 'RolePlai',
    url: 'https://roleplai.app/',
    description: 'An AI-based role-playing chat platform where users can interact with AI-generated virtual characters, supporting custom storylines and gamified experiences.',
    highlights: 'Provides immersive narrative experiences, suitable for users who enjoy story-driven games.',
    category: 'Interactive Fiction'
  },
  {
    title: 'AI Dungeon',
    url: 'https://play.aidungeon.com/',
    description: 'AI-driven text adventure game',
    category: 'Interactive Fiction',
    icon: 'https://play-lh.googleusercontent.com/9zvNJHOoq4JhGngfEzNOr5HrCXvvVWgGrjJ_Zj7GNxGkJkAYZBbX3gFT0GtUgx4jRA=w240-h480-rw'
  },
  {
    title: 'Emooji',
    url: 'https://www.emooji.lol/',
    description: 'AI-driven picture game platform',
    category: 'Picture Games',
    icon: 'https://www.emooji.lol/favicon.ico'
  },
  {
    title: 'Quick Draw',
    url: 'https://quickdraw.withgoogle.com/',
    description: 'Google\'s AI recognition doodle interactive game',
    category: 'Picture Games',
    icon: 'https://storage.googleapis.com/gweb-uniblog-publish-prod/images/quickdraw_icon.max-500x500.png'
  },
  {
    title: 'Hidden Door',
    url: 'https://www.hiddendoor.co/',
    description: 'A role-playing game platform that supports users creating and participating in role-playing adventures.',
    highlights: 'User-friendly interface, strong character customization, active community.',
    category: 'Role-Playing Games',
    subcategory: ''
  },
  {
    title: 'Infinite Craft',
    url: 'https://neal.fun/infinite-craft/',
    description: 'An infinite creativity crafting game where players can create various items starting from basic elements.',
    highlights: 'Infinite creativity, simple gameplay, suitable for relaxation.',
    category: 'Fun Websites',
    subcategory: ''
  },
  {
    title: 'Hexagen World',
    url: 'https://www.hexagen.world/',
    description: 'A strategy game world based on hexagons where players can explore and build.',
    highlights: 'Unique hexagonal design, strong strategy elements, excellent visual effects.',
    category: 'Fun Websites',
    subcategory: ''
  },
  {
    title: 'Ifable AI',
    url: 'https://www.ifable.ai/start',
    description: 'An AI-driven game design platform that supports developers in quickly building game prototypes.',
    highlights: 'AI-assisted design, rapid prototype development, suitable for independent developers.',
    category: 'Game Design',
    subcategory: 'Game Engine'
  },
  {
    title: 'Playroom',
    url: 'https://joinplayroom.com/',
    description: 'A multiplayer online game platform supporting various types of games and social interactions.',
    highlights: 'Diverse game selection, real-time multiplayer interaction, rich community features.',
    category: 'Fun Websites',
    subcategory: ''
  },
  {
    title: 'Human or Not',
    url: 'https://humanornot.so/',
    description: 'An interactive game where players need to judge whether the interlocutor is human or AI.',
    highlights: 'Unique game concept, tests player insight, clean interface.',
    category: 'Puzzle Games',
    subcategory: ''
  },
  {
    title: 'ChessGPT',
    url: 'https://chessgpt.atomic14.com/',
    description: 'A chess game combined with AI technology, supporting AI battles and learning.',
    highlights: 'Intelligent AI opponent, suitable for players of different levels, intuitive interface.',
    category: 'Strategy Games',
    subcategory: ''
  },
  {
    title: 'AI2U With You Til The End',
    url: 'https://store.steampowered.com/app/2880730/AI2U_With_You_Til_The_End/',
    description: 'A narrative-driven adventure game where players explore stories with an AI companion.',
    highlights: 'Emotionally rich storyline, beautiful visual effects, strong interactivity.',
    category: 'Adventure Games',
    subcategory: ''
  },
  {
    title: 'The Simulation',
    url: 'https://ww1.thesimulation.co/?usid=16&utid=37464761826',
    description: 'A sandbox simulation game where players can create and manage their own virtual world.',
    highlights: 'Highly free gameplay, rich simulation elements, suitable for strategy enthusiasts.',
    category: 'Strategy Games',
    subcategory: 'Sandbox Simulation'
  },
  {
    title: 'Oasis',
    url: 'https://oasis.decart.ai/welcome',
    description: 'An AI-driven creative platform supporting users in generating art and design.',
    highlights: 'AI-generated art, user-friendly interface, infinite creativity.',
    category: 'Game Design',
    subcategory: 'Story and Character Design'
  },
  {
    title: 'WebSim',
    url: 'https://websim.ai/',
    description: 'A web-based simulation platform supporting users in creating and sharing simulation scenarios.',
    highlights: 'Easy to use, community sharing features, suitable for education and entertainment.',
    category: 'Strategy Games',
    subcategory: 'Sandbox Simulation'
  },
  {
    title: 'Human or AI',
    url: 'https://humanizeai.com/human-or-ai/',
    description: 'An interactive experience where players need to judge whether text is human or AI-generated.',
    highlights: 'Simple and fun, suitable for quick games, clean interface.',
    category: 'Puzzle Games',
    subcategory: ''
  },
  {
    title: 'Charmed AI',
    url: 'https://charmed.ai/',
    description: 'An AI-driven character design tool supporting game developers in quickly creating characters.',
    highlights: 'AI-assisted design, character diversity, suitable for rapid prototyping.',
    category: 'Game Design',
    subcategory: 'Story and Character Design'
  },
  {
    title: 'Genie 2 by DeepMind',
    url: 'https://deepmind.google/discover/blog/genie-2-a-large-scale-foundation-world-model/',
    description: 'DeepMind\'s blog post introducing a large-scale foundation world model.',
    highlights: 'Cutting-edge AI research, potential game development applications, technical depth.',
    category: 'Game Design',
    subcategory: 'Game Engine'
  },
  {
    title: 'My Adventures AI',
    url: 'https://myadventures.ai/',
    description: 'An AI-generated adventure game platform where players can experience personalized adventure stories.',
    highlights: 'AI-driven storylines, highly interactive, suitable for adventure enthusiasts.',
    category: 'Adventure Games',
    subcategory: ''
  },
  {
    title: 'Endless VN',
    url: 'https://endlessvn.io/',
    description: 'An infinite visual novel platform where players can explore endless storylines.',
    highlights: 'Infinite story possibilities, visual novel style, attractive interface.',
    category: 'Interactive Fiction',
    subcategory: ''
  },
  {
    title: 'Smarter Than GPT',
    url: 'https://smarterthangpt.com/',
    description: 'A game design tool platform providing a more intelligent solution than GPT.',
    highlights: 'Advanced AI technology, suitable for developers, professional interface.',
    category: 'Game Design',
    subcategory: 'Game Engine'
  },
  {
    title: 'Ready Player Me',
    url: 'https://readyplayer.me/',
    description: 'A virtual character creation platform supporting users in creating avatars for games and applications.',
    highlights: 'Highly customizable characters, cross-platform compatibility, easy integration.',
    category: 'Game Design',
    subcategory: 'Story and Character Design'
  },
  {
    title: 'V3 RPG',
    url: 'https://landing.v3rpg.com/',
    description: 'A role-playing game platform supporting players in creating and participating in RPG adventures.',
    highlights: 'Rich character customization, community-driven content, user-friendly interface.',
    category: 'Role-Playing Games',
    subcategory: ''
  }
];